services:
  app:
    build:
      context: .
      target: dev
    volumes:
      - .:/app
    env_file:
      - .env.dev
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: postgres
    env_file:
      - .env.dev
    ports:
      - 5432:5432